The Apple page clone project
RNtaate/roy-apple-page-project pull request #1
Opened 2020-05-15 09:03 UTC by RNtaate

In this project, I created a clone of an Apple web page, used gradient and background images in styling the backgrounds of most of the HTML elements used in the project.

2020-05-16 02:56 UTC, sumancrest0001 reviewed
STATUS: CHANGES REQUIRED
Impressive work @RNtaate 
Most of the requirements are ticked and you are very close to getting approval for this project. Let's fix the following issues and make it better.

2020-05-16 02:58 UTC, sumancrest0001 commented on index.html
> +    </div>
Let's add a link to each article as in the [original](https://web.archive.org/web/20140301004610/http://www.apple.com/) one.

2020-05-16 02:59 UTC, sumancrest0001 commented on styler.css
> +
We have to clean up the CSS file and remove all the repeated code. Let's follow the DRY principle.

2020-05-16 03:00 UTC, sumancrest0001 commented on styler.css
> +
We have to clean up the CSS file and remove all the repeated code. Let's follow the DRY principle.

2020-05-16 03:02 UTC, sumancrest0001 requested changes
Kindly make the request changes and submit another review form. I am sure that it won't take a long time to make these changes.

Need help or have a query? Contact me on slack **Suman Shrestha**
**Happy coding**

2020-05-18 08:49 UTC, RNtaate commented
Removed all repeated code in the from the CSS file and added a link to each article in the lower-sec-div just as in the original one.

2020-05-19 00:07 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/RNtaate/roy-apple-page-project/apple-b/index.html) shows good understanding and usage of building with backgrounds and gradients. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that, you just have to update the live link to match the changes and you should be good.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @RNtaate! :+1:
- Carry out the change with the live link and then merge this. You don't have to submit another code review. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-05-19 08:53 UTC, merged